#models : ['vgg19_bn', 'resnet34', 'resnet50', 'densenet121']
model : 'vgg19_bn'
pretrained : True

fine_tuning : True
tune_epochs : 5

train_epochs : 10
batch_size : 16
num_workers : 8

weight_decay : 1e-4
learning_rate : 0.01
momentum : 0.9
optimizer : SGD


# data locations
images_dir : './images'
labels_dir : './image_data/sample_labels.csv'
image_mean : [0.485, 0.456, 0.406]
image_std  : [0.229, 0.224, 0.225]
class_labels : 14

path_labels : [ 'Atelectasis','Cardiomegaly', 'Effusion', 'Infiltration', 'Mass', 'Nodule', 'Pneumonia', 'Pneumothorax',
            'Consolidation', 'Edema', 'Emphysema',  'Fibrosis', 'Pleural_Thickening', 'Hernia']

nih_labels_csv : 'nih_labels.csv'

